apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sg8scxa82-go-gitops
  description: This is GitOps manifest for sg8scxa82-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: sg8scxa82-go
    janus-idp.io/tekton: sg8scxa82-go
    backstage.io/kubernetes-id: sg8scxa82-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sg8scxa82-go
