apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sg8scxa82-go
  janus-idp.io/tekton: sg8scxa82-go
  backstage.io/kubernetes-id: sg8scxa82-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sg8scxa82-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
