apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sg8scxa82-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sg8scxa82-go 
  name: sg8scxa82-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sg8scxa82-go 
